### PR TITLE
Add providers for linux_ppc64le and linux_aarch64.

### PR DESCRIPTION
**Pull request by bdice**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bdice** [comment]
@conda-forge-admin, please rerender

**Comment by hmaarrfk** [comment]
i think this should be redone in light of 3.0

**Comment by chrisburr** [comment]
I tried in #10 but I also enabled more features which means there are dependencies missing.

I'll add the bot re-run label so they get picked up first.

**Comment by chrisburr** [comment]
Ah this isn't a bot PR! I've opened a PR to add this to the migration: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/758

**Comment by bdice** [comment]
@hmaarrfk @chrisburr Thanks for fixing / finishing this up! 🚀

**Comment by hmaarrfk** [comment]
Np

**Pull request closed without merging**
