### PR TITLE
Update to 3.0.0

### PR DESCRIPTION
**Pull request by chrisburr**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by chrisburr** [comment]
@conda-forge/htop Ready for review. Also, if you don't mind, I added myself to the list of maintainers?

**Comment by hmaarrfk** [comment]
exciting.

**Comment by chrisburr** [comment]
@conda-forge/core Can someone take a look and merge? I've already added myself to the maintainers.

`htop` 3.0.0 is actually a fork but its [blessed by the original developer](https://github.com/hishamhm/htop#htop) and [quite a few distributions](https://repology.org/project/htop/versions) have started building their `htop` packages from it (including Debian and Fedora).

**Comment by xhochy** [comment]
Thanks @chrisburr !

**Comment by chrisburr** [comment]
Thanks @xhochy!

**Pull request merged**
